name: Build Hugo
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Check out theme
      uses: actions/checkout@master
        with:
          repository: theNewDynamic/gohugo-theme-ananke
          path: hugo/themes/ananke
    - name: Build Hugo
      uses: lowply/build-hugo@v0.73.0
